### ISSUE TITLE
Font sizes too small on mobile

### ISSUE THREAD

**Issue by skylarng89** [obidient/23ForObiFrontend#1]
On mobile view, the font sizes of some elements like buttons and the text on the cards are too tiny.

![Screenshot_20220630-142217_Samsung Internet.jpg](https://user-images.githubusercontent.com/1462747/176688717-f1c80467-df7b-49f5-af69-71364cbe0a7c.jpg)

**Comment by PeroHub** [comment]
> On mobile view, the font sizes of some elements like buttons and the text on the cards are too tiny.
> 
> ![Screenshot_20220630-142217_Samsung Internet.jpg](https://user-images.githubusercontent.com/1462747/176688717-f1c80467-df7b-49f5-af69-71364cbe0a7c.jpg)

What font size should it carry on a mobile device and can I work on this? @skylarng89 @odizee

**Comment by odizee** [comment]
This has been worked on. Have you checked the latest version of the website?
