### ISSUE TITLE
Top 5 contributor text

### ISSUE THREAD

**Issue by odizee** [obidient/23ForObiFrontend#105]
If there is no contributor, don't show this text at all. If there is one contributor, then add the text "Delivered by:" and put just the person there
![WhatsApp Image 2022-07-24 at 8 25 36 PM](https://user-images.githubusercontent.com/66241926/180740937-dacfc5c1-009f-407a-8c70-dd5d94549711.jpeg)

**Comment by kuicpet** [comment]
done
