### ISSUE TITLE
Implement lightbox on social media images

### ISSUE THREAD

**Issue by odizee** [obidient/23ForObiFrontend#36]
Clicking any of these images should pop it up and then show some buttons for you to share it on Facebook, WhatsApp, Twitter.
![WhatsApp Image 2022-07-04 at 11 36 27 PM](https://user-images.githubusercontent.com/66241926/177314802-5835bd0f-de5f-45ab-b494-b6940dff1c9b.jpeg)

**Comment by kuicpet** [comment]
done
