### ISSUE TITLE
Text colours on some elements are faint

### ISSUE THREAD

**Issue by skylarng89** [obidient/23ForObiFrontend#4]
The colour of the text on some elements like "Vote Control", the progress bars are faint and a little hard to see. A much darker black will look better. Also the font weight of 300 doesn't look like the best to use. A font weight of 400 could make the difference.

**Comment by PeroHub** [comment]
> The colour of the text on some elements like "Vote Control", the progress bars are faint and a little hard to see. A much darker black will look better. Also the font weight of 300 doesn't look like the best to use. A font weight of 400 could make the difference.

I just checked the Figma board, "vote control" has the same color as what is implemented. Is there still a need to make it darker? @skylarng89
