### ISSUE TITLE
"Add a group" pop up modal.

### ISSUE THREAD

**Issue by odizee** [obidient/23ForObiFrontend#40]
"Add a group" should pop up a modal where you can enter the info. After entering info and they submit, prompt them to login

![WhatsApp Image 2022-07-04 at 11 34 07 PM](https://user-images.githubusercontent.com/66241926/177317228-973b532f-5fd5-4648-b426-07199906ff29.jpeg)

**Comment by PeroHub** [comment]
> "Add a group" should pop up a modal where you can enter the info. After entering info and they submit, prompt them to login
> 
> ![WhatsApp Image 2022-07-04 at 11 34 07 PM](https://user-images.githubusercontent.com/66241926/177317228-973b532f-5fd5-4648-b426-07199906ff29.jpeg)

I'll work on this
