### ISSUE TITLE
Add click function to state cards

### ISSUE THREAD

**Issue by odizee** [obidient/23ForObiFrontend#5]
Clicking the whole card should take the user to the state or village
![Screenshot (37)](https://user-images.githubusercontent.com/66241926/176733642-96e14a5c-faaa-44f3-9d20-91da8cb6e789.png)
.

**Comment by Chiziivictor** [comment]
For better user experience, the whole card might be too much... I suggest just the heading of the card should handle the click...

**Comment by odizee** [comment]
> For better user experience, the whole card might be too much... I suggest just the heading of the card should handle the click...
Great. That will be better.
